
services:
  - type: web
    name: manus-backend
    runtime: python3
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        sync: false
      - key: API_BASE
        value: "https://api.openai.com/v1"
      - key: MODEL_NAME
        value: "gpt-4o"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: "INFO"

  - type: web
    name: manus-frontend
    runtime: node
    buildCommand: "cd frontend && npm ci && npm run build"
    startCommand: "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"
    plan: free
    staticPublishPath: ./frontend/dist

  - type: redis
    name: manus-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: manus-mongodb
    databaseName: manus
    user: manus
