
---
- name: Deploy AI Manus Application
  hosts: servers
  become: yes
  vars:
    app_name: manus-ai
    app_user: manus
    app_dir: /opt/manus
    
  tasks:
    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/bash
        home: "{{ app_dir }}"
        create_home: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Copy application files
      copy:
        src: "../"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'

    - name: Copy environment file
      template:
        src: .env.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0600'

    - name: Start application with Docker Compose
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present
        build: yes
      become_user: "{{ app_user }}"

    - name: Setup systemd service
      template:
        src: manus.service.j2
        dest: /etc/systemd/system/manus.service
        mode: '0644'
      notify:
        - reload systemd
        - start manus

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: start manus
      systemd:
        name: manus
        state: started
        enabled: yes
